(() => {
  'use strict';
  const $ = (s) => document.querySelector(s), arr = (v) => Array.isArray(v) ? v : [];
  const esc = (v) => String(v ?? '').replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[c]);
  const safeUrl = (v) => /^https?:\/\//i.test(String(v || '')) ? esc(v) : '';
  const state = { data: null, page: 'home', taskFilter: '未完了', meetingFilter: 'すべて', day: '', tab: 'summary' };
  const speaker = (v) => state.data?.speaker_names?.[v] || v || '話者未設定';
  const link = (url) => safeUrl(url) ? `<a class="notion-link" href="${safeUrl(url)}" target="_blank" rel="noopener">Notionで開く ↗</a>` : '';
  const fmt = (v) => v ? esc(String(v).replace('T', ' ').replace(/:\d\d(?:[+-].*)?$/, '')) : '—';
  const updated = (v) => { const d = new Date(v); return Number.isNaN(d.getTime()) ? '—' : `${d.getMonth() + 1}/${d.getDate()} ${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`; };
  const label = (v) => { const d = new Date(`${v}T00:00:00`); return `${esc(v)} ${Number.isNaN(d.getTime()) ? '' : ['日','月','火','水','木','金','土'][d.getDay()] + '曜日'}`; };
  const empty = (v = '表示できる記録はありません') => `<p class="empty">${esc(v)}</p>`;
  const setView = (html) => { $('#view').innerHTML = html; bind(); };

  function db() { return new Promise((ok, ng) => { const r = indexedDB.open('work-brief-key', 1); r.onupgradeneeded = () => r.result.createObjectStore('keys'); r.onsuccess = () => ok(r.result); r.onerror = () => ng(r.error); }); }
  async function getKey() { try { const d = await db(); return await new Promise((ok, ng) => { const r = d.transaction('keys').objectStore('keys').get('main'); r.onsuccess = () => ok(r.result); r.onerror = () => ng(r.error); }); } catch { return null; } }
  async function putKey(value) { const d = await db(); return new Promise((ok, ng) => { const r = d.transaction('keys', 'readwrite').objectStore('keys').put(value, 'main'); r.onsuccess = ok; r.onerror = () => ng(r.error); }); }
  async function clearKey() { try { const d = await db(); await new Promise((ok, ng) => { const r = d.transaction('keys', 'readwrite').objectStore('keys').clear(); r.onsuccess = ok; r.onerror = () => ng(r.error); }); } catch {} }
  const b64 = (v) => Uint8Array.from(atob(v), (c) => c.charCodeAt(0));
  async function derive(pass, env) { const material = await crypto.subtle.importKey('raw', new TextEncoder().encode(pass), 'PBKDF2', false, ['deriveKey']); return crypto.subtle.deriveKey({ name: 'PBKDF2', hash: 'SHA-256', salt: b64(env.salt), iterations: Number(env.iter) }, material, { name: 'AES-GCM', length: 256 }, false, ['decrypt']); }
  async function decode(env, key) { const bytes = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: b64(env.iv) }, key, b64(env.ct)); let stream = new Blob([bytes]).stream(); if (env.gzip) { if (!window.DecompressionStream) throw new Error('gzip非対応'); stream = stream.pipeThrough(new DecompressionStream('gzip')); } return JSON.parse(await new Response(stream).text()); }
  async function unlock(pass) { const res = await fetch('data.enc.json', { cache: 'no-cache' }); if (!res.ok) throw new Error('data'); const env = await res.json(), old = await getKey(); try { let key; if (!pass && old && old.salt === env.salt) key = old.key; else if (pass) key = await derive(pass, env); else throw new Error('need'); state.data = await decode(env, key); if (pass) await putKey({ salt: env.salt, key }); $('#updated').textContent = `最終更新 ${updated(state.data.generated_at)}`; $('#lock').classList.add('hidden'); $('#app').classList.remove('hidden'); render(); } catch (e) { if (!pass && old) await clearKey(); if (pass) throw e; } }

  function urgent() { const now = new Date(`${String(state.data.today || '2100-01-01').slice(0,10)}T00:00:00`), groups = { '期限切れ': [], '今日期限': [], '承認待ち': [], 'あと2日': [], '停滞': [] }; arr(state.data.tasks).filter((t) => !['完了','却下'].includes(t.status)).forEach((t) => { const d = t.due ? new Date(`${String(t.due).slice(0,10)}T00:00:00`) : null; if (d && d < now) groups['期限切れ'].push(t); else if (d && d.getTime() === now.getTime()) groups['今日期限'].push(t); else if (t.status === '要確認') groups['承認待ち'].push(t); else if (d && (d-now)/86400000 <= 2) groups['あと2日'].push(t); else if (t.status === '未着手' && t.created_time && (now-new Date(t.created_time))/86400000 > 7) groups['停滞'].push(t); }); return groups; }
  function home() { const needs = Object.entries(urgent()).flatMap(([n, ts]) => ts.slice(0,2).map((t) => `<li><b>${esc(n)}</b> ${esc(t.title)}</li>`)); const days = arr(state.data.daily).slice().sort((a,b) => String(b.date).localeCompare(String(a.date)));
    const alert = state.data.health?.alert;
    const alertHtml = alert ? `<section class="alert"><p class="eyebrow">処理の異常</p><h2>${esc(alert.title)}</h2>${alert.detail ? `<p>${esc(alert.detail)}</p>` : ''}<p class="calm">PC側の夜間処理が止まっています。それまでこのアプリの内容は更新されません。</p></section>` : '';
    setView(`<section class="page-title"><h1>録音の記録</h1><p>日ごとの会話と要点を確認できます</p></section>${alertHtml}<button class="search-row" data-action="search">⌕　要約・会話・人物を検索</button><section class="attention"><div class="section-line"><div><p class="eyebrow">今日の要対応</p><h2>${needs.length}件</h2></div><button data-page="tasks" class="text-button">タスクを見る</button></div>${needs.length ? `<ul>${needs.join('')}</ul>` : '<p class="calm">期限が近い未完了タスクはありません。</p>'}</section>${arr(state.data.meetings).length ? `<div class="section-line"><h2 class="section-title">最近の議事録</h2><button data-page="meetings" class="text-button">すべて見る</button></div>${arr(state.data.meetings).slice(0,2).map(meetingCard).join('')}` : ''}<h2 class="section-title">日別の録音</h2>${days.length ? days.map((d) => `<button class="day-card" data-day="${esc(d.date)}"><div class="day-card-head"><div><b>${label(d.date)}</b><span>${esc(d.tone || '')}</span></div><span>›</span></div><p>${esc(d.summary || '要約はありません')}</p><div class="chips"><span>${Math.round(Number(d.speech_min)||0)}分 発話</span><span>${Number(d.sessions)||0}会話</span><span>${Number(d.people_count)||0}人</span>${Number(d.risk_count) ? `<em>リスク ${Number(d.risk_count)}</em>` : ''}${Number(d.meeting_count) ? '<em class="meeting">会議あり</em>' : ''}</div></button>`).join('') : empty()}`); }
  function tasks() { const data = arr(state.data.tasks).filter((t) => state.taskFilter === 'すべて' || (state.taskFilter === '未完了' ? !['完了','却下'].includes(t.status) : t.status === state.taskFilter)).sort((a,b) => String(a.due||'9999').localeCompare(String(b.due||'9999'))); setView(`<section class="page-title"><h1>タスク</h1><p>変更はNotionで行います</p></section><button class="filter-button" data-action="filter">${esc(state.taskFilter)} <span>⌄</span></button>${data.length ? data.map((t) => `<article class="task-card"><div class="task-head"><div><h2>${esc(t.title || '名称未設定')}</h2><p>${esc(t.genre || '')}${t.person ? ` ・ ${esc(t.person)}` : ''}</p></div><span class="status ${statusClass(t.status)}">${esc(t.status || '未設定')}</span></div><p class="due">${t.due ? `期限 ${fmt(t.due)}` : '期限未設定'}</p>${t.quote ? `<blockquote>${esc(t.quote)}</blockquote>` : ''}${link(t.url)}</article>`).join('') : empty('該当するタスクはありません')}`); }
  function personDays(p) { const names = new Set([p.name, p.id]); return Object.entries(state.data.daily_detail || {}).filter(([,d]) => arr(d.people).some((x) => names.has(x.name_guess) || names.has(speaker(x.speaker_label)) || x.speaker_label === p.id)).sort(([a],[b]) => b.localeCompare(a)); }
  function people() { const list = arr(state.data.people).slice().sort((a,b) => (/^(未設定|不明|話者)/.test(b.name||'') ? 1 : 0) - (/^(未設定|不明|話者)/.test(a.name||'') ? 1 : 0) || Number(b.count||0)-Number(a.count||0)); setView(`<section class="page-title"><h1>人物</h1><p>会話に登場した人をたどる</p></section>${list.length ? list.map((p) => `<button class="person-card" data-person="${esc(p.id)}"><div><h2>${esc(p.name||'名前未設定')}</h2><p>${esc([p.org,p.relation].filter(Boolean).join(' ・ '))}</p></div><div class="person-meta"><b>${Number(p.count)||0}回</b><span>${fmt(p.last_seen)}</span></div></button>`).join('') : empty()}`); }
  // 一覧は「未設定」を先頭に並べ替えて表示するので、並び順の番号ではなくIDで引く
  function personDetail(id) { const p = arr(state.data.people).find((x) => x.id === id); if (!p) return; const days = personDays(p); setView(`<button class="back" data-back="people">‹ 人物へ戻る</button><section class="page-title"><h1>${esc(p.name||'名前未設定')}</h1><p>${esc([p.org,p.relation].filter(Boolean).join(' ・ '))}</p></section>${p.memo ? `<details class="memo"><summary>メモ</summary><p>${esc(p.memo)}</p></details>` : ''}<h2 class="section-title">登場した日</h2>${days.length ? days.map(([date,d]) => `<button class="day-card compact" data-day="${esc(date)}"><b>${label(date)}</b><p>${esc(d.summary||'')}</p></button>`).join('') : empty('登場日の詳細はありません')}${link(p.url)}`); }
  function more() { setView(`<section class="page-title"><h1>その他</h1><p>案件とナレッジ</p></section><button class="more-row" data-action="threads">案件 <span>${arr(state.data.threads).length}件　›</span></button><button class="more-row" data-action="knowledge">ナレッジ <span>${arr(state.data.knowledge).length}件　›</span></button><button class="more-row" data-action="settings">設定 <span>›</span></button>`); }
  function threads() { const list = arr(state.data.threads); setView(`<button class="back" data-back="more">‹ その他へ戻る</button><section class="page-title"><h1>案件</h1></section>${list.length ? list.map((t) => `<article class="task-card"><div class="task-head"><h2>${esc(t.name)}</h2><span class="status ${statusClass(t.status)}">${esc(t.status)}</span></div><p>${esc(t.next_action||'')}</p><p class="muted">最終言及 ${fmt(t.last_mention)}</p>${link(t.url)}</article>`).join('') : empty()}`); }
  function knowledge() { const list = arr(state.data.knowledge); setView(`<button class="back" data-back="more">‹ その他へ戻る</button><section class="page-title"><h1>ナレッジ</h1></section>${list.length ? list.map((k,i) => `<button class="more-row" data-knowledge="${i}">${esc(k.name)} <span>${fmt(k.updated)}　›</span></button>`).join('') : empty()}`); }
  function knowledgeDetail(i) { const k = arr(state.data.knowledge)[i]; if (k) setView(`<button class="back" data-back="knowledge">‹ ナレッジへ戻る</button><section class="page-title"><h1>${esc(k.name)}</h1><p>${fmt(k.updated)}</p></section><article class="read-card markdown">${markdown(k.text)}</article>`); }

  const bullets = (v) => arr(v).length ? `<ul>${arr(v).map((x) => `<li>${esc(x)}</li>`).join('')}</ul>` : '';
  const section = (title, html) => html ? `<section class="detail-section"><h2>${title}</h2>${html}</section>` : '';
  // 議事録: 日付をまたいで一覧し、開くと議題ごとの経緯・決定・やることを全部見せる
  function kindClass(kind) { return ({ '朝礼': 'kind-morning', '研修': 'kind-training', '会議': 'kind-meeting', '打ち合わせ': 'kind-talk', '商談': 'kind-sales' })[kind] || 'kind-meeting'; }
  function meetingCard(m) { const lead = m.purpose || arr(m.agenda).map((a) => a.topic).filter(Boolean).slice(0,3).join('・'); return `<button class="meeting-card list" data-meeting="${esc(m.id)}"><div class="meeting-head"><span class="kind-badge ${kindClass(m.kind)}">${esc(m.kind || '会議')}</span><span class="muted">${label(m.date)}${m.time ? ` ・ ${esc(m.time)}` : ''}</span></div><b>${esc(m.title)}</b>${lead ? `<p>${esc(lead)}</p>` : ''}<p class="muted">${arr(m.attendees).length ? `${arr(m.attendees).length}人参加 ・ ` : ''}議題 ${arr(m.agenda).length}件 ・ 決定 ${arr(m.decisions).length}件${arr(m.todos).length ? ` ・ やること ${arr(m.todos).length}件` : ''}</p></button>`; }
  function meetings() { const all = arr(state.data.meetings); const kinds = ['すべて', ...new Set(all.map((m) => m.kind || '会議'))]; const list = all.filter((m) => state.meetingFilter === 'すべて' || (m.kind || '会議') === state.meetingFilter); setView(`<section class="page-title"><h1>議事録</h1><p>会議・研修・朝礼・打ち合わせを自動で記録</p></section><div class="chip-row">${kinds.map((k) => `<button class="chip ${k === state.meetingFilter ? 'selected' : ''}" data-meeting-filter="${esc(k)}">${esc(k)}${k === 'すべて' ? ` ${all.length}` : ` ${all.filter((m) => (m.kind || '会議') === k).length}`}</button>`).join('')}</div>${list.length ? list.map(meetingCard).join('') : empty('議事録はまだありません。10分以上・2人以上の会話から自動で作られます')}`); }
  function meetingDetail(id) { const m = arr(state.data.meetings).find((x) => x.id === id); if (!m) return; const agenda = arr(m.agenda).map((a, i) => `<article class="agenda-item"><b>${i + 1}. ${esc(a.topic)}</b>${a.discussion ? `<p>${esc(a.discussion)}</p>` : ''}${a.conclusion ? `<p class="conclusion">結論　${esc(a.conclusion)}</p>` : ''}</article>`).join(''); const todos = arr(m.todos).map((t) => `${t.what}${t.who ? `（${t.who}）` : ''}${t.due ? `　期限 ${t.due}` : ''}`); setView(`<button class="back" data-back="meetings">‹ 議事録へ戻る</button><section class="page-title"><span class="kind-badge ${kindClass(m.kind)}">${esc(m.kind || '会議')}</span><h1>${esc(m.title)}</h1><p>${label(m.date)}${m.time ? ` ・ ${esc(m.time)}` : ''}</p></section>${m.purpose ? `<article class="summary-lead">${esc(m.purpose)}</article>` : ''}${arr(m.attendees).length ? `<div class="chips attendees">${arr(m.attendees).map((a) => `<span>${esc(speaker(a))}</span>`).join('')}</div>` : ''}${section('議題', agenda)}${section('決定事項', bullets(m.decisions))}${section('やること', bullets(todos))}${section('持ち越し・未決', bullets(m.pending))}${section('メモ', bullets(m.notes))}${state.data.daily_detail?.[m.date] ? `<button class="more-row" data-day="${esc(m.date)}">この日の記録を見る <span>›</span></button>` : ''}`); }
  function summary(d) { const risks = arr(d.risks).map((r) => `<article class="risk ${sevClass(r.severity)}"><b>${esc(r.severity)} · ${esc(r.category)}</b><p>${esc(r.why)}</p>${r.action ? `<p>対応: ${esc(r.action)}</p>` : ''}${r.quote ? `<blockquote>${esc(r.quote)}</blockquote>` : ''}</article>`).join(''); const meetings = arr(d.meetings).map((m) => { const full = arr(state.data.meetings).find((x) => x.date === state.day && x.title === m.title); return full ? meetingCard(full) : `<article class="meeting-card"><b>${esc(m.title)}</b><p>${esc(m.time)} · ${esc(m.kind)}</p>${bullets(arr(m.agenda).map((a) => `${a.topic||''}：${a.conclusion||a.discussion||''}`))}</article>`; }).join(''); const questions = arr(d.questions).map((q) => `<article class="meeting-card"><b>${esc(q.question)}</b><p>${esc(q.why)}</p>${arr(d.research).filter((r) => r.question === q.question).map((r) => `<p>${esc(r.answer)}</p>`).join('')}</article>`).join(''); return `<article class="summary-lead">${esc(d.summary||'要約はありません')}${link(d.notion_url)}</article>${section('決定事項',bullets(d.decisions))}${section('気づき',bullets(d.insights))}${section('ハイライト',bullets(d.highlights))}${section('リスク',risks)}${section('議事録',meetings)}${section('疑問と調べた答え',questions)}`; }
  function sessions(d) { return arr(d.sessions).length ? `<div class="timeline">${arr(d.sessions).map((s) => `<button class="session-card" data-session="${esc(String(s.id))}"><span>${esc(s.time)}</span><div><b>${esc(s.title||'会話')}</b><p>${arr(s.participants).map((x) => esc(speaker(x))).join(' ・ ')}</p><p>${esc(s.summary||'')}</p>${bullets(s.points)}</div></button>`).join('')}</div>` : empty('会話記録はありません'); }
  function transcripts(d) { const rows = arr(state.data.transcripts?.[state.day]); if (!rows.length) return empty('この日の文字起こしはありません'); const titles = new Map(arr(d.sessions).map((s) => [String(s.id),s.title])); let previous = ''; return rows.map((r) => { const id = String(r.session), title = id !== previous ? `<h2 id="session-${esc(id)}" class="transcript-session">${esc(titles.get(id)||`会話 ${id}`)}</h2>` : ''; previous=id; return `${title}<article class="utterance"><span class="avatar" style="--hue:${speakerHue(r.speaker)}">${esc(avatarText(speaker(r.speaker)))}</span><div><b>${esc(speaker(r.speaker))}</b><time>${esc(r.start||'')}</time><p>${esc(r.text)}</p></div></article>`; }).join(''); }
  // 文字起こしの丸アイコンの文字。名前未設定の人は全員「未」になって見分けがつかないので、声紋IDの番号を出す
  function avatarText(name) {
    const text = String(name || '');
    const unset = text.match(/^未設定\s*P?0*(\d+)/);
    if (unset) return unset[1].slice(-3);
    const label = text.match(/^P0*(\d+)$/);
    return label ? label[1].slice(-3) : text.slice(0, 1);
  }

  // 状態・重大度を色分けするためのクラス名（日本語の値をそのままクラスにしない）
  function statusClass(status) {
    return { '未着手': 'st-todo', '要確認': 'st-review', '進行中': 'st-doing', '待ち': 'st-review',
             '保留': 'st-hold', '完了': 'st-done', '却下': 'st-rejected', '流れた': 'st-rejected' }[status] || 'st-hold';
  }
  function sevClass(severity) {
    return { '高': 'sev-high', '中': 'sev-mid', '低': 'sev-low' }[severity] || 'sev-low';
  }

  // 話者ごとに色を固定する（同じ声紋IDなら毎回同じ色）
  function speakerHue(label) {
    let h = 0;
    for (const ch of String(label || '')) h = (h * 31 + ch.codePointAt(0)) % 360;
    return h;
  }

  // ナレッジ用の最小限のMarkdown表示（見出し・箇条書き・引用・太字）。先にエスケープしてから整形する
  function markdown(text) {
    const inline = (s) => esc(s).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
    let html = '', list = false, quote = false;
    const close = () => {
      if (list) { html += '</ul>'; list = false; }
      if (quote) { html += '</blockquote>'; quote = false; }
    };
    for (const line of String(text || '').split('\n')) {
      const h = line.match(/^(#{1,3})\s+(.*)$/), li = line.match(/^\s*[-*]\s+(.*)$/), q = line.match(/^>\s?(.*)$/);
      if (h) { close(); html += `<h${h[1].length + 1}>${inline(h[2])}</h${h[1].length + 1}>`; }
      else if (li) { if (quote) close(); if (!list) { html += '<ul>'; list = true; } html += `<li>${inline(li[1])}</li>`; }
      else if (q) { if (list) close(); if (!quote) { html += '<blockquote>'; quote = true; } html += `${inline(q[1])}<br>`; }
      else if (!line.trim()) close();
      else { close(); html += `<p>${inline(line)}</p>`; }
    }
    close();
    return html;
  }

  // mermaid の図形記法（root((…)), (…), […], {{…}}, ))…(( など）を外して見出しの文字だけにする
  function mindmapLabel(line) {
    return line.trim()
      .replace(/^[-*]\s*/, '')
      .replace(/^root(?=[(\[{)])/, '')
      .replace(/^[(\[{)]+\s*(.*?)\s*[)\]}(]+$/, '$1');
  }

  function mindmap(d) { const nodes=String(d.mindmap||'').split('\n').filter((x)=>x.trim()&&!/^mindmap\s*$/i.test(x.trim())); return nodes.length ? `<div class="mindmap-tree">${nodes.map((x) => { const depth=Math.floor((x.match(/^\s*/)||[''])[0].length/2); return `<details class="mind-node" open style="--depth:${Math.min(depth,8)}"><summary>${esc(mindmapLabel(x))}</summary></details>`; }).join('')}</div>` : empty('マインドマップはありません'); }
  function detail(day) { const d=state.data.daily_detail?.[day]; if(!d)return; state.day=day; state.tab='summary'; const s=d.stats||{}; setView(`<button class="back" data-back="home">‹ 録音一覧へ戻る</button><section class="page-title"><h1>${label(day)}</h1><p>${esc(d.tone||'')}</p></section><div class="stat-row"><span>録音 ${Math.round(Number(s.recorded_min)||0)}分</span><span>発話 ${Math.round(Number(s.speech_min)||0)}分</span><span>${Number(s.sessions)||0}会話</span></div><div class="segments"><button data-tab="summary" class="active">要約</button><button data-tab="sessions">会話</button><button data-tab="transcripts">文字起こし</button><button data-tab="mindmap">マップ</button></div><div id="detailContent"></div>`); renderTab(); }
  function renderTab() { const d=state.data.daily_detail?.[state.day]; if(!d)return; document.querySelectorAll('[data-tab]').forEach((b)=>b.classList.toggle('active',b.dataset.tab===state.tab)); $('#detailContent').innerHTML=state.tab==='summary'?summary(d):state.tab==='sessions'?sessions(d):state.tab==='transcripts'?transcripts(d):mindmap(d); bind(); }
  // シートの中身を差し込んだ直後にbind()し直す。これが無いと、状態の絞り込みや
  // 「記憶を消す」など、シート内のボタンがクリックしても何も起きない
  function openSheet(html) { $('#sheet').innerHTML=html; $('#sheetBack').classList.add('show'); $('#sheet').classList.add('show'); bind(); }
  function closeSheet() { $('#sheetBack').classList.remove('show'); $('#sheet').classList.remove('show'); }
  function search() { openSheet('<h2>横断検索</h2><input id="searchInput" placeholder="要約・文字起こし・タスク・人物を検索"><div id="results" class="muted">キーワードを入力してください</div>'); const input=$('#searchInput'); input.focus(); input.oninput=()=>{const q=input.value.trim().toLowerCase();if(!q){$('#results').textContent='キーワードを入力してください';return;}const out=[];const add=(type,title,sub,action,value)=>{if(`${title} ${sub}`.toLowerCase().includes(q))out.push(`<button class="result" data-result="${action}" data-value="${esc(value)}"><b>${esc(type)}　${esc(title)}</b><span>${esc(sub||'')}</span></button>`);};arr(state.data.daily).forEach((x)=>add('日別',x.date,x.summary,'day',x.date));arr(state.data.tasks).forEach((x)=>add('タスク',x.title,x.quote,'page','tasks'));arr(state.data.people).forEach((x)=>add('人物',x.name,x.memo,'person',x.id));arr(state.data.meetings).forEach((x)=>add('議事録',x.title,`${x.date} ${x.purpose||''} ${arr(x.agenda).map((a)=>a.topic).join(' ')} ${arr(x.decisions).join(' ')}`,'meeting',x.id));Object.entries(state.data.transcripts||{}).forEach(([day,rows])=>arr(rows).forEach((r)=>add('文字起こし',speaker(r.speaker),r.text,'day',day)));$('#results').innerHTML=out.slice(0,40).join('')||'<p class="muted">一致する記録はありません</p>';bind();}; }
  function settings() { openSheet('<h2>設定</h2><p class="muted">この端末に保存した合言葉の鍵を消します。次回は合言葉の入力が必要です。</p><button class="danger" data-action="forget">この端末の記憶を消す</button>'); }
  function render() { document.querySelectorAll('.bottom-nav button').forEach((b)=>b.classList.toggle('active',b.dataset.page===state.page)); ({home,tasks,people,meetings,more}[state.page]||home)(); }
  function bind() { document.querySelectorAll('[data-page]').forEach((b)=>b.onclick=()=>{state.page=b.dataset.page;render();});document.querySelectorAll('[data-day]').forEach((b)=>b.onclick=()=>detail(b.dataset.day));document.querySelectorAll('[data-person]').forEach((b)=>b.onclick=()=>personDetail(b.dataset.person));document.querySelectorAll('[data-back]').forEach((b)=>b.onclick=()=>{state.page=b.dataset.back;render();});document.querySelectorAll('[data-tab]').forEach((b)=>b.onclick=()=>{state.tab=b.dataset.tab;renderTab();});document.querySelectorAll('[data-session]').forEach((b)=>b.onclick=()=>{state.tab='transcripts';renderTab();setTimeout(()=>document.querySelector(`#session-${CSS.escape(b.dataset.session)}`)?.scrollIntoView({behavior:'smooth'}),0);});document.querySelectorAll('[data-action="search"]').forEach((b)=>b.onclick=search);document.querySelectorAll('[data-action="filter"]').forEach((b)=>b.onclick=()=>openSheet(`<h2>状態で絞り込む</h2>${['未完了','未着手','要確認','進行中','完了','却下','すべて'].map((x)=>`<button class="sheet-choice ${x===state.taskFilter?'selected':''}" data-filter="${x}">${x}</button>`).join('')}`));document.querySelectorAll('[data-filter]').forEach((b)=>b.onclick=()=>{state.taskFilter=b.dataset.filter;closeSheet();tasks();});document.querySelectorAll('[data-action="threads"]').forEach((b)=>b.onclick=threads);document.querySelectorAll('[data-action="knowledge"]').forEach((b)=>b.onclick=knowledge);document.querySelectorAll('[data-action="settings"]').forEach((b)=>b.onclick=settings);document.querySelectorAll('[data-knowledge]').forEach((b)=>b.onclick=()=>knowledgeDetail(Number(b.dataset.knowledge)));document.querySelectorAll('[data-meeting]').forEach((b)=>b.onclick=()=>meetingDetail(b.dataset.meeting));document.querySelectorAll('[data-meeting-filter]').forEach((b)=>b.onclick=()=>{state.meetingFilter=b.dataset.meetingFilter;meetings();});document.querySelectorAll('[data-result]').forEach((b)=>b.onclick=()=>{closeSheet();if(b.dataset.result==='day')detail(b.dataset.value);else if(b.dataset.result==='person')personDetail(b.dataset.value);else if(b.dataset.result==='meeting')meetingDetail(b.dataset.value);else{state.page=b.dataset.value;render();}});document.querySelectorAll('[data-action="forget"]').forEach((b)=>b.onclick=async()=>{await clearKey();closeSheet();}); }
  $('#sheetBack').onclick=closeSheet; $('#searchButton').onclick=search; $('#unlockForm').onsubmit=async(e)=>{e.preventDefault();const pass=$('#passphrase').value;if(!pass)return;$('#lockError').textContent='';try{await unlock(pass);$('#passphrase').value='';}catch{$('#lockError').textContent='合言葉が正しくないか、データを開けません。';}}; if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{}); unlock().catch(()=>{});
})();
